django_projects/account/urls.py
from django.urls import path

from account import views

app_name = 'account'
urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('signin/', views.sign_in, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.sign_out, name='signout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
]

django_projects/app1/urls.py
from django.urls import path

from app1 import views


urlpatterns = [
    path('', views.sign_in, name='signin'),
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
    path('user_list/', views.user_list, name='user_list'),
    path('logout/', views.sign_out, name='signout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

]

django_projects/django_projects/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('account.urls')),
    path('', include('ecommerce.urls', namespace='ecommerce')),
]

django_projects/ecommerce/urls.py
from django.urls import path

from ecommerce import views

app_name = 'ecommerce'

urlpatterns = [
    path('listings/', views.listing_page, name='listings'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('cart/<int:product_id>/<str:size>/', views.add_to_cart, name='add_to_cart'),
    path('cart', views.cart, name='cart'),
    path('search', views.search, name='search'),
    path('delete_cart_item/<int:item_id>/', views.delete_cart_item, name='delete_cart_item'),
    path('update_quantity/<int:item_id>/<str:action>/', views.update_quantity),
    path('clear_cart/', views.clear_cart, name='clear_cart'),
    path('checkout/', views.checkout, name='checkout'),
]

django_projects/ecommerce/models.py
import uuid

from django.core.validators import MinValueValidator
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    brand = models.CharField(max_length=250)
    currency = models.CharField(max_length=3)
    lang = models.CharField(max_length=2)
    market = models.CharField(max_length=2)
    name = models.CharField(max_length=500)
    price = models.FloatField(validators=[MinValueValidator(0.0)])
    gender = models.CharField(max_length=6)
    retailer_sku = models.CharField(max_length=20, unique=True, primary_key=True)
    trail = models.CharField(max_length=500)
    url = models.TextField()


class ImageURL(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='image_urls')
    color = models.CharField(max_length=50)
    url = models.URLField()

    def __str__(self):
        return self.url


class SKU(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='skus')
    sku = models.CharField(max_length=50)
    color = models.CharField(max_length=50)
    price = models.FloatField(validators=[MinValueValidator(0.0)])
    size = models.CharField(max_length=10)
    currency = models.CharField(max_length=3)
    out_of_stock = models.BooleanField()

    def __str__(self):
        sku_dict = {
            'sku': self.sku,
            'color': self.color,
            'price': self.price,
            'size': self.size,
            'currency': self.currency,
            'out_of_stock': self.out_of_stock,
        }
        return str(sku_dict)


class Description(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='description')
    content = models.CharField(max_length=250)

    def __str__(self):
        return self.content


class Care(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='care')
    content = models.CharField(max_length=250)

    def __str__(self):
        return self.content


class Category(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='category')
    category = models.CharField(max_length=50)

    def __str__(self):
        return self.category


class CartItem(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1)])
    size = models.CharField(max_length=10, default='One Size')


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    order_id = models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True)
    order_date = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=100)
    shipping_address = models.TextField()
    contact_info = models.CharField(max_length=100)
    total_price = models.DecimalField(max_digits=10, decimal_places=2)
    expected_delivery_date = models.DateTimeField()

    def __str__(self):
        return f"Order ID: {self.order_id}"


class OrderedItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='order')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

    def __str__(self):
        return f"{self.product.name} - {self.quantity}"

django_projects/ecommerce/forms.py
from django import forms
from django.core.validators import MinLengthValidator, MaxLengthValidator


class CheckoutForm(forms.Form):
    PAYMENT_METHOD_CHOICES = [
        ('credit_card', 'Credit Card'),
        ('easypaisa', 'EasyPaisa'),
        ('bank_transfer', 'Bank Transfer'),
        ('cash_on_delivery', 'Cash on Delivery')
    ]

    payment_method = forms.ChoiceField(choices=PAYMENT_METHOD_CHOICES, widget=forms.RadioSelect)
    shipping_address = forms.CharField(max_length=500)
    contact_info = forms.CharField(
        max_length=11,
        validators=[MinLengthValidator(11), MaxLengthValidator(11)],
        help_text="Please enter your 11-digit contact number."
    )

django_projects/ecommerce/views.py
from datetime import timedelta

from django.shortcuts import render, redirect
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.http import JsonResponse
from django.utils import timezone
from django.db import transaction
from django.db.models.signals import post_save


from ecommerce.models import Product, Order, OrderedItem
from ecommerce.forms import CheckoutForm


def listing_page(request):
    products = Product.objects.all()

    paginator = Paginator(products, 50)
    page_number = request.GET.get('page')
    pages = paginator.get_page(page_number)

    products = []
    for product in pages:
        image_urls = product.image_urls.all()
        skus = product.skus.all()
        products.append({
            'product': product,
            'image_urls': image_urls,
            'skus': skus
        })

    return render(request, 'ecommerce/listings.html', {'listings': products, 'pages': pages})


def product_detail(request, product_id):
    product = Product.objects.get(retailer_sku=product_id)

    image_urls = product.image_urls.all()
    descriptions = product.description.all()
    cares = product.care.all()
    categories = product.category.all()
    skus = product.skus.all()
    data = {
        'product': product,
        'image_urls': image_urls,
        'descriptions': descriptions,
        'cares': cares,
        'categories': categories,
        'skus': skus
    }

    return render(request, 'ecommerce/product_detail.html', data)


@login_required(login_url='account:signin')
def add_to_cart(request, product_id, size):
    product = Product.objects.get(retailer_sku=product_id)

    if 'cart_items' not in request.session:
        request.session['cart_items'] = {}

    cart_items = request.session['cart_items']

    if product.retailer_sku in cart_items:
        cart_items[product.retailer_sku]['quantity'] += 1
    else:
        cart_items[product.retailer_sku] = {
            'retailer_sku': product.retailer_sku,
            'size': size,
            'quantity': 1
        }

    request.session.modified = True

    return redirect('ecommerce:cart')


@login_required(login_url='account:signin')
def cart(request):
    cart_items_data = request.session.get('cart_items', {})
    total_price = sum(
        Product.objects.get(retailer_sku=item['retailer_sku']).price * item['quantity']
        for item in cart_items_data.values()
    )
    context = {
        'cart_items_data': cart_items_data,
        'total_price': total_price,
    }

    return render(request, 'ecommerce/cart.html', context)


def search(request):
    query = request.GET.get('query')
    products = Product.objects.filter(Q(name__icontains=query) | Q(brand__icontains=query))
    listings = []
    for product in products:
        image_urls = product.image_urls.all()
        skus = product.skus.all()
        listings.append({
            'product': product,
            'image_urls': image_urls,
            'skus': skus
        })

    return render(request, 'ecommerce/search.html', {'listings': listings, 'query': query})


@login_required(login_url='account:signin')
def update_quantity(request, item_id, action):
    cart_items_data = request.session.get('cart_items', {})

    if str(item_id) in cart_items_data:
        if action == "increase":
            cart_items_data[str(item_id)]['quantity'] += 1
        elif action == "decrease" and cart_items_data[str(item_id)]['quantity'] > 1:
            cart_items_data[str(item_id)]['quantity'] -= 1
        request.session.modified = True

    return JsonResponse({"success": True})


@login_required(login_url='account:signin')
def clear_cart(request):
    if 'cart_items' in request.session:
        del request.session['cart_items']
        request.session.modified = True

    return JsonResponse({"success": True})


@login_required(login_url='account:signin')
def delete_cart_item(request, item_id):
    cart_items_data = request.session.get('cart_items', {})

    if str(item_id) in cart_items_data:
        del cart_items_data[str(item_id)]
        request.session.modified = True

    return JsonResponse({"success": True})


@login_required(login_url='account:signin')
def checkout(request):
    cart_items_data = request.session.get('cart_items', {})
    selected_item_ids = request.GET.get('selected_items')
    selected_item_ids_list = [int(item_id) for item_id in selected_item_ids.split(',')]
    selected_cart_items = [cart_items_data[str(item_id)] for item_id in selected_item_ids_list]
    total_price = sum(
        Product.objects.get(retailer_sku=item['retailer_sku']).price * item['quantity']
        for item in selected_cart_items
    )

    if request.method == 'POST':
        form = CheckoutForm(request.POST)
        order_date = timezone.now()
        expected_delivery_date = order_date + timedelta(days=5)

        if form.is_valid():
            payment_method = form.cleaned_data['payment_method']
            shipping_address = form.cleaned_data['shipping_address']
            contact_info = form.cleaned_data['contact_info']

            with transaction.atomic():
                order = Order.objects.create(
                    user=request.user,
                    order_date=order_date,
                    expected_delivery_date=expected_delivery_date,
                    payment_method=payment_method,
                    shipping_address=shipping_address,
                    contact_info=contact_info,
                    total_price=total_price
                )

                ordered_items = [
                    OrderedItem(
                        order=order,
                        product=Product.objects.get(retailer_sku=cart_item['retailer_sku']),
                        quantity=cart_item['quantity']
                    )
                    for cart_item in selected_cart_items
                ]

                OrderedItem.objects.bulk_create(ordered_items)
                post_save.send(sender=OrderedItem, instance=ordered_items[-1], created=True)

                cart_items_data = [
                    {
                        'product_name': Product.objects.get(retailer_sku=item['retailer_sku']).name,
                        'size': item['size'],
                        'quantity': item['quantity'],
                    }
                    for item in selected_cart_items
                ]

                context = {
                    'order': order,
                    'total_price': total_price,
                    'cart_items_data': cart_items_data,
                    'total_price': total_price
                }

                return render(request, 'ecommerce/order_confirmation.html', context)

    form = CheckoutForm()
    context = {
        'form': form,
        'cart_items': selected_cart_items,
        'total_price': total_price,
    }

    return render(request, 'ecommerce/checkout.html', context)

django_projects/templates/ecommerce/cart.html
{% load static %}
{% load product_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cart</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/cart.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="{% static 'ecommerce/cart.js' %}"></script>
</head>
<body>
    <nav class="navbar">
        <div class="nav-content">
            <a class="logo" href="{% url 'ecommerce:listings' %}">Sleek  Boutique</a>
            <ul class="nav-links">
                <li><a href="{% url 'ecommerce:listings' %}">Our Products</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'account:profile' %}">Profile</a></li>
                <li><a href="{% url 'ecommerce:cart' %}"><i class="fa fa-shopping-cart"></i></a></li>
                <li><a href="{% url 'account:signout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'account:signin' %}">Sign In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    {% if total_price|floatformat:2 != "0.00" %}
    <h1>Your Cart <i class="fa fa-shopping-cart"></i></h1>
    
    <table class="cart-table">
        <tr>
            <th></th>
            <th>Product</th>
            <th>Size</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Action</th>
        </tr>
        {% for cart_item_id, cart_item in cart_items_data.items %}
<tr>
    <td><input type="checkbox" name="selected_items" value="{{ cart_item_id }}"></td>
    <td>{% with product=cart_item.retailer_sku|get_product %}
        {{ product.name}}
        {% endwith %}
    </td>
    <td>{{ cart_item.size }}</td>
    <td>
        <button class="quantity-btn" data-action="decrease" data-item="{{ cart_item_id }}">-</button>
        {{ cart_item.quantity }}
        <button class="quantity-btn" data-action="increase" data-item="{{ cart_item_id }}">+</button>
    </td>
    <td>
        {% with product=cart_item.retailer_sku|get_product %}
        {{ product.price|floatformat:2 }} {{ product.currency }}
        {% endwith %}
    </td>
    <td>
        <a href="javascript:void(0);" onclick="deleteCartItem({{ cart_item_id }})">
            <i class="fa fa-trash"></i>
        </a>
    </td>
</tr>
{% endfor %}
        <tr>
            <td colspan="4"><strong>Total</strong></td>
            <td><strong>{{ total_price|floatformat:2 }} {{ cart_items_data.0.product.currency }}</strong></td>
        </tr>
    </table>
    <div class="cart-actions">
        <a href="{% url 'ecommerce:checkout' %}" class="checkout-btn">Checkout</a>
        <a href="{% url 'ecommerce:clear_cart' %}" class="clear-cart-btn">Clear Cart</a>
    </div>
    {% else %}
    <h1>Your Cart is empty <i class="fa fa-frown-o"></i></h1>
    {% endif %}
    
</body>
</html>

django_projects/templates/ecommerce/checkout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/checkout.css' %}">
    <title>Checkout</title>
</head>
<body>
    <nav class="navbar">
        <div class="nav-content">
            <a class="logo" href="{% url 'ecommerce:listings' %}">Sleek  Boutique</a>
            <ul class="nav-links">
                <li><a href="{% url 'ecommerce:listings' %}">Our Products</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'account:profile' %}">Profile</a></li>
                <li><a href="{% url 'ecommerce:cart' %}"><i class="fa fa-shopping-cart"></i></a></li>
                <li><a href="{% url 'account:signout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'account:signin' %}">Sign In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <h1>Checkout</h1>

    <form method="post">
        {% csrf_token %}
        
        <div class="checkout-section">
            <h2>Shipping Information</h2>
            {{ form.shipping_address }}
        </div>
        <div class="checkout-section">
            <h2>Contact Number</h2>
            {{ form.contact_info }}<br>
           {{form.contact_info.help_text}}
        </div>

        <div class="checkout-section">
            <h2>Payment Method</h2>
            {{ form.payment_method }}
        </div>
        <div class="checkout-section">
            <h2>Order Summary</h2>
            <p>Total Price: <strong>{{ total_price|floatformat:2 }} {{ cart_items.0.product.currency }}</strong></p>
        </div>
        <input type="hidden" name="selected_items" value="{{ selected_item_ids|join:',' }}">
        <button type="submit" class="checkout-btn">Place Order</button>
    </form>

</body>
</html>

django_projects/templates/ecommerce/listings.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/product.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="{% static 'ecommerce/listings.js' %}"></script>
    <title>listings</title>
</head>
<body>
  <nav class="navbar">
    <div class="nav-content">
        <a class="logo" href="{% url 'ecommerce:listings' %}">Sleek  Boutique</a>
        <ul class="nav-links">
            <li><a href="{% url 'ecommerce:listings' %}">Our Products</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'account:profile' %}">Profile</a></li>
            <li><a href="{% url 'ecommerce:cart' %}"><i class="fa fa-shopping-cart"></i></a></li>
            <li><a href="{% url 'account:signout' %}">Logout</a></li>
            {% else %}
            <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
            <li><a href="{% url 'account:signin' %}">Sign In</a></li>
            {% endif %}
        </ul>
        <form class="search-form" action="{% url 'ecommerce:search' %}" method="GET">
            <input type="text" name="query" placeholder="Search products">
            <button type="submit">Search</button>
        </form>
    </div>
</nav>
    <h1 class="title-heading">Latest Arrival</h1>
    <div class="listings">
        {% for listing_data in listings %}
          <div class="listing">
            <h2>{{ listing_data.product.name }}</h2>
            <img src="{{ listing_data.image_urls.0|safe }}" alt="{{ listing_data.product.name }} Image">
            <p>{{ listing_data.product.price }} {{ listing_data.product.currency }}</p>
            <p><strong> {{ listing_data.product.brand }}</strong></p>
            <select class="size-options" id="size-{{ listing_data.product.retailer_sku }}">
              {% for sku in listing_data.skus %}
                  <option value="{{ sku.size }}">{{ sku.size }}</option>
              {% endfor %}
          </select>
          
          <div class="listing-links">
              <a href="{% url 'ecommerce:product_detail' listing_data.product.retailer_sku %}">View Details</a>
              <a class="add-to-cart-link" href="{% url 'ecommerce:add_to_cart' product_id=listing_data.product.retailer_sku size='default' %}">Add to cart</a>

          </div>
          </div>
        {% endfor %}
      </div>
      <div class="pagination">
       
        <span class="page-links">
          {% for page in pages.paginator.page_range %}
              <a href="?page={{ page }}">{{ page }}</a>
          {% endfor %}
        </span>
      </div>
</body>

</html>

django_projects/templates/ecommerce/order_confirmation.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Order Confirmation</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/order_confirmation.css' %}">
</head>
<body>
    <nav class="navbar">
        <div class="nav-content">
            <a class="logo" href="{% url 'ecommerce:listings' %}">Sleek  Boutique</a>
            <ul class="nav-links">
                <li><a href="{% url 'ecommerce:listings' %}">Our Products</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'account:profile' %}">Profile</a></li>
                <li><a href="{% url 'ecommerce:cart' %}"><i class="fa fa-shopping-cart"></i></a></li>
                <li><a href="{% url 'account:signout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'account:signin' %}">Sign In</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="order-confirmation">
        <div class="thank-you">
            <h1>Thank You!</h1>
            <p>Your order has been successfully placed.</p>
        </div>
        <div class="order-summary">
            <h2>Order Summary</h2>
            <p><strong>Order ID:</strong> {{ order.order_id }}</p>
            <p><strong>Shipping Address:</strong> {{ order.shipping_address }}</p>
            <p><strong>Order Date:</strong> {{ order.order_date }}</p>
            <p><strong>Expected Delivery Date:</strong> {{ order.expected_delivery_date }}</p>
            <p><strong>Email:</strong> {{ order.user.email }}</p>
            <p><strong>Contact Number:</strong> {{ order.contact_info }}</p>
            <p><strong>Payment Method:</strong> {{ order.payment_method }}</p>
            <h3>Items in Cart:</h3>
            <ul class="cart-items">
                {% for cart_item in cart_items_data %}
                <li>{{ cart_item.product_name }} (Size: {{ cart_item.size }}) - Quantity: {{ cart_item.quantity }}</li>
                {% endfor %}
            </ul>
            <p><strong>Total Price:</strong> {{ total_price }}</p>
        </div>
        
    </div>
</body>
</html>

django_projects/templates/ecommerce/product_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/product_detail.css' %}">
    <script type="text/javascript" src="{% static 'ecommerce/product_detail.js' %}"></script>
    <title>Product Detail</title>
</head>
<body>
    <nav class="navbar">
        <div class="nav-content">
            <a class="logo" href="{% url 'ecommerce:listings' %}">Sleek  Boutique</a>
            <ul class="nav-links">
                <li><a href="{% url 'ecommerce:listings' %}">Our Products</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'account:profile' %}">Profile</a></li>
                <li><a href="{% url 'ecommerce:cart' %}"><i class="fa fa-shopping-cart"></i></a></li>
                <li><a href="{% url 'account:signout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'account:signin' %}">Sign In</a></li>
                {% endif %}
            </ul>
            <form class="search-form" action="{% url 'ecommerce:search' %}" method="GET">
                <input type="text" name="query" placeholder="Search products">
                <button type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="product-detail">
        <h2>{{ product.name }}</h2>
        <div class="categories">{% for point in categories %}
                > {{ point }}
            {% endfor %}
        </div>
        <div class="product-images">
        {% for image_url in image_urls %}
        <img src="{{ image_url|safe }}" alt="{{ product.name }}">
        {% endfor %}
        </div>
        <p><strong>Brand: </strong>{{ product.brand }}</p>
        <p><strong>Price: </strong>{{ product.price }} {{ product.currency }}</p>
        <p><strong>Description: </strong></p>
        <ul>
            {% for point in descriptions %}
                <li>{{ point }}</li>
            {% endfor %}
            <li>For {{ product.gender }}</li>
        </ul>
        <p><strong>Care: </strong></p>
        <ul>
            {% for point in cares %}
                <li>{{ point }}</li>
            {% endfor %}
        </ul>
        <div class="size-and-cart-container">
            <div>
            <strong>Select Size: </strong>
            <select class="size-options" id="size-{{ product.retailer_sku }}">
                {% for sku in skus %}
                    <option value="{{ sku.size }}">{{ sku.size }}</option>
                {% endfor %}
            </select>
            </div>
        <div>
            <a class="add-to-cart-link" href="{% url 'ecommerce:add_to_cart' product_id=product.retailer_sku size='default' %}">Add to cart</a>
        </div>
    </div>
        <table>
            <thead>
                <tr>
                    <th>Color</th>
                    <th>Size</th>
                    <th>Price</th>
                </tr>
            </thead>
            <tbody>
                {% for sku in skus %}
                    <tr>
                        <td>{{ sku.color }}</td>
                        <td>{{ sku.size }}</td>
                        <td>{{ sku.price }} {{ sku.currency }}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
       
    </div>
    
    
    
</body>
  
</html>

django_projects/templates/ecommerce/search.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/search.css' %}">
    <title>listings</title>
</head>
<body>
    <nav class="navbar">
        <div class="nav-content">
            <a class="logo" href="{% url 'ecommerce:listings' %}">Sleek  Boutique</a>
            <ul class="nav-links">
                <li><a href="{% url 'ecommerce:listings' %}">Our Products</a></li>
                {% if user.is_authenticated %}
                <li><a href="{% url 'account:profile' %}">Profile</a></li>
                <li><a href="{% url 'ecommerce:cart' %}"><i class="fa fa-shopping-cart"></i></a></li>
                <li><a href="{% url 'account:signout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
                <li><a href="{% url 'account:signin' %}">Sign In</a></li>
                {% endif %}
            </ul>
            <form class="search-form" action="{% url 'ecommerce:search' %}" method="GET">
                <input type="text" name="query" placeholder="Search products">
                <button type="submit">Search</button>
            </form>
        </div>
    </nav>

<h1 class="title-heading">Search Results for "{{ query }}"</h1>
    <div class="listings">
        {% for listing_data in listings %}
            <div class="listing">
                <h2>{{ listing_data.product.name }}</h2>
                <img src="{{ listing_data.image_urls.0|safe }}" alt="{{ listing_data.product.name }} Image">
                <p>{{ listing_data.product.price }} {{ listing_data.product.currency }}</p>
                <p><strong>{{ listing_data.product.brand }}</strong></p>
                <select class="size-options" id="size-{{ listing_data.product.retailer_sku }}">
                    {% for sku in listing_data.skus %}
                        <option value="{{ sku.size }}">{{ sku.size }}</option>
                    {% endfor %}
                </select>
                <div class="listing-links">
                    <a href="{% url 'ecommerce:product_detail' listing_data.product.retailer_sku %}">View Details</a>
                    <a class="add-to-cart-link" href="{% url 'ecommerce:add_to_cart' product_id=listing_data.product.retailer_sku size='default' %}">Add to cart</a>
                </div>
            </div>
        {% endfor %}
    </div>
    <div class="pagination">
        <span class="page-links">
            {% for page in pages.paginator.page_range %}
                <a href="?page={{ page }}">{{ page }}</a>
            {% endfor %}
        </span>
    </div>
</body>
</html>